# Generated by Django 5.2.1 on 2025-08-11 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_score', models.FloatField(default=100)),
                ('final_exam_full_score', models.FloatField(default=50)),
                ('midterm_full_score', models.FloatField(default=20)),
                ('section_exam_full_score', models.FloatField(default=15)),
                ('year_work_full_score', models.FloatField(default=15)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.course')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='accounts.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_score', models.FloatField(default=0)),
                ('section_exam_score', models.FloatField(default=0)),
                ('final_exam_score', models.FloatField(default=0)),
                ('year_work_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('letter_grade', models.CharField(blank=True, max_length=2)),
                ('is_passed', models.BooleanField(default=False)),
                ('grade_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='grades.gradesheet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('grade_sheet', 'student')},
            },
        ),
    ]
