# Generated by Django 5.2.1 on 2025-08-11 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('role', models.CharField(choices=[('subject_doctor', 'دكتور مادة'), ('admin_doctor', 'دكتور إداري'), ('teaching_assistant', 'معيد')], default='subject_doctor', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['national_id'], name='accounts_do_nationa_23a446_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('national_id', models.CharField(max_length=14)),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True)),
                ('sec_num', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['national_id'], name='accounts_st_nationa_bcf65f_idx')],
            },
        ),
    ]
