# Generated by Django 5.2.1 on 2025-08-11 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_doctor_structures_student_structure'),
        ('courses', '0002_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('slot_number', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('Lecture', 'Lecture'), ('Section', 'Section')], default='Lecture', editable=False, help_text="Automatically set to 'Lecture' if section is 'All'", max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='courses.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc', to='accounts.doctor')),
                ('student_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='structure.studentstructure')),
            ],
        ),
    ]
