# Generated by Django 5.2.1 on 2025-08-11 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSectionAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASSED', 'ناجح'), ('FAILED', 'راسب'), ('SUMMER', 'سمر كورس'), ('FAILED_AFTER_SUMMER', 'راسب بعد السمر كورس'), ('RETAKE_YEAR', 'إعادة السنة')], default='FAILED', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'subject_doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.doctor')),
            ],
        ),
    ]
