# Generated by Django 5.2.1 on 2025-08-11 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_structure', to='structure.studentstructure'),
        ),
        migrations.AddField(
            model_name='coursesectionassistant',
            name='assistant',
            field=models.ForeignKey(limit_choices_to={'role': 'teaching_assistant'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='coursesectionassistant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assistants', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stucourses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='accounts.student'),
        ),
    ]
