# Generated by Django 5.2.1 on 2025-08-11 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('DATA', 'Data Science'), ('CYBER', 'Cyber Security'), ('AUTOTRONICS', 'Autotronics'), ('MECHATRONICS', 'Mechatronics'), ('GARMENT_MANUFACTURING', 'Garment Manufacturing'), ('CONTROL_SYSTEMS', 'Control Systems')], max_length=25)),
                ('year', models.CharField(choices=[('First', 'First Year'), ('Second', 'Second Year'), ('Third', 'Third Year'), ('Fourth', 'Fourth Year')], max_length=6)),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('passed', 'Passed'), ('summer', 'Summer Course'), ('retake_year', 'Retake Year')], default='passed', max_length=20)),
                ('failed_courses_names', models.JSONField(blank=True, default=list)),
                ('failed_courses', models.ManyToManyField(blank=True, related_name='failed_structures', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='FailedSummerCourseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('First', 'First Year'), ('Second', 'Second Year'), ('Third', 'Third Year'), ('Fourth', 'Fourth Year')], max_length=6)),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=6)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SummerCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
